project:
  type: website

website:
  title: "Introduction to Machine Learning Using Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    toc: true
  revealjs:
    theme: [solarized]
    echo: true
    logo: img/kuleuven.png

execute:
  freeze: true
