project:
  type: website

website:
  title: "Introduction to Machine Learning Using Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    highlight-style: pygments
  revealjs:
    theme: [solarized, custom.scss]
    echo: true
    code-overflow: wrap
    logo: img/kuleuven.png
    highlight-style: pygments

execute:
  freeze: true
