project:
  type: website

website:
  title: "Introduction to Machine Learning Using Python"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
  revealjs:
    theme: [solarized, custom.scss]
    echo: true


