---
title: "About this course"
format: html
---

# Content

- Fundamentals of Python: I know that the course website says that the focus lies on "NLP, automation, text analysis and machine learning", but I find it more important to give you a strong basis that helps you feel confident about learning more and gives you the tools to understand tutorials and documentation. We'll adjust the speed to the students.

- We'll try to cover actual fundamentals in the first half, i.e. before easter: types of variables, working with lists and dictionaries, creating functions, using classes, but also opening and saving files, using regular expressions, parsing XML.

- In the second half we will put the regular expressions and parsing into practice and check out packages for machine learning (scikit-learn) and NLP (nltk, maybe spacy). We'll also look a bit into testing and documenting, so that you still understand next year what you tried to do today.

# Assignments
- There will be a final assignment that consists of solving a problem with Python code and explaining it/documenting it. For those submitting in June, it will be 80% fo the grade. For those submitting in August, it will be a bit more complex and account for 100% of the grade.

- I will propose problems that you can try to solve, but we can also brainstorm and discuss ideas during the semester as you learn more about the contents.
- There will be two small assignments during the semester: one due after Easter and one that is a presentation at the end of the semester. Each of them accounts for 10% of the grade.

# Requirements

Make sure they all have Anaconda (as late a version as possible) and VS Code installed.

Each class:

- Open Anaconda

- Select (in Home) or create (in Environments) the appropriate environment. For the first classes we can use a basic one with no additional packages.

- In Home, make sure that Jupyter Notebook and VS Code are installed for your environment.

- Open Jupyter Notebook and from its file explored find your way to the folder where you store the scripts for this class. Open an existing notebook or create a new one, as appropriate. Try out the code from the slides in that notebook.

- After some experimentation, open VS Code to write a small script and run it in the console. Depending on the rhythm of the class, this might be the last task or something to do at home.
