---
title: "Second assignment"
format: html
---

::: callout-important
## Dates

**Due** on 23-05-2023. If you think you may not be able to attend, you can do it on 16-05-2023.

:::

# Assignment description

Present the plan for your final project to your classmates and the lecturer. You may prepare slides or not.
Like with the first assignment, it is worth 2 out of the total 20 points of the course.

In your presentation:

- Explain the problem that your program tries to solve.

- Explain how your program tries to solve it.

- Be as didactic and transparent as you can about how you approach the problem and what skills learned in class you are using.

Your project doesn't have to be fully fledged by the time you give a presentation, but at least you should have enough of an idea of how to approach your problem, with the technical implementation as nailed down as possible.

It is perfectly ok if your presentation exposes weaknesses of your approach or code: use this opportunity to figure them out and get advice!

While not part of the assignment, it would be great if you could also participate in your classmates' assignments giving them feedback on the clarity and completeness of their work.
